### ISSUE TITLE
issue summary from Cat

### ISSUE THREAD

**Issue by eosnas** [USFWS/mdeditor-user-guide-alaska-region#1]
Hi Erik,

I was tasked to send you mdE U.G. issues. In no particular order (except for maybe the first one which is overarching):

1) review and revise the U.G. to ensure consistency with the Interim Data Management User Guide V.2 (dated 8/30/2019).  

2) revise import/export guidance to make clear that source data mdE JSON files are saved to the source data folder in the archive folder and all project related product records, data dictionaries, and contacts and imported/exported en mass as a single file to the metadata folder in the archive folder.  

3) provide guidance on where to record QA and QC information. Long term, support for QC info will be implemented in the mdEditor. In the near term, will likely need to use the lineage section to describe how data moved from version to version due to QC efforts.   

4) Location of the product (e.g. an excel file) in the archive record should be recorded under Distribution: Transfer: Online Options: URI. If everyone uses the single server set up by IT and dedicated for the purpose of archiving, that should eliminate the need to reference the true server name (not the letter assigned by each user in the network drives), but guidance should be given as to which part of the folder address is required.  

5) Source data (as defined in the Interim DM User Guide) used in the development of a product should be documented in the lineage section of a product. 

That was my working list. Thanks, 

Cat

**Comment by jlblcc** [comment]
> 4. Location of the product (e.g. an excel file) in the archive record should be recorded under Distribution: Transfer: Online Options: URI. If everyone uses the single server set up by IT and dedicated for the purpose of archiving, that should eliminate the need to reference the true server name (not the letter assigned by each user in the network drives), but guidance should be given as to which part of the folder address is required.

The fully qualified domain name of the server will still need to be included. For eaxmple, in the case of the Regional archive, the location should start with `file://ifw7ro-file.fws.doi.net/Datamgt/`. To test, copy and paste the file URI into a browser or Explorer, example: `file://ifw7ro-file.fws.doi.net/Datamgt/Test/test.txt`

Also, I would suggest splitting these up into separate issues.

**Comment by mccrea-cobb** [comment]
I split these up as distinct issues.
