### ISSUE TITLE
mdEditor suggestion: Metadata Records "Time Period"

### ISSUE THREAD

**Issue by lamcduffie** [USFWS/mdeditor-user-guide-alaska-region#11]
Currently a start and end date is required for the time period in Metadata Records "Main" tab. If a project is currently active, an end date should not be required. Also, If you chose to select date by fiscal year, the year only goes as far back as 2009. We have active projects that started well before 2009. I suggest you add dates back into the early 90s at least.

**Comment by jlblcc** [comment]
Either a `start date` or `end date` is required. You can enter only the `start date`. Entering at least one will remove the error from the other field. The error message could be improved to say 'One of start or end date is required'.

The fiscal year select is just a convenience feature, adding that many years would make it less user-friendly. However, you can generate FY dates for _any_ by typing in the input that appears at the top of the select list.

![image](https://user-images.githubusercontent.com/5833603/68233420-a2f58280-ffab-11e9-9747-c5e5b0e3a709.png)

---

![image](https://user-images.githubusercontent.com/5833603/68233437-ad178100-ffab-11e9-95ce-20380dd6e8f4.png)
