### ISSUE TITLE
mdEditor suggestion: Automatically add data dictionaries to "Dictionaries" tab

### ISSUE THREAD

**Issue by lamcduffie** [USFWS/mdeditor-user-guide-alaska-region#12]
A required portion of the Metadata Records "Main" tab is to add Resource Type. It would be amazing if once a data dictionary is names and created as a new resource type, it is automatically added to the listed dictionaries in the "Dictionaries" tab. Additionally, this would automatically check the box in the Dictionaries "Main" tab where it asks if "Dictionary is included with the resource?".

**Comment by jlblcc** [comment]
I'm not quite clear what the ask is here.
