### ISSUE TITLE
mdEditor suggestion: Responsible Party

### ISSUE THREAD

**Issue by lamcduffie** [USFWS/mdeditor-user-guide-alaska-region#13]
Currently only one responsible party can be added to data dictionaries under the "main" tab. Instead of the blue dot on the right-hand side, there should be an "Add +" button.

**Comment by jlblcc** [comment]
Only one Responsible Party is supported by the [metadata schema](https://www.adiwg.org/mdTools/#viewer-page?v=4-0-5). You can add multiple contacts, they'll just share the same role.
