### ISSUE TITLE
mdEditor suggestion: Import CSV

### ISSUE THREAD

**Issue by lamcduffie** [USFWS/mdeditor-user-guide-alaska-region#14]
Import CSV is EXTREMELY difficult to find and frustrating.  Currently there is no option to import a CSV when adding an Entity for the first time. The Import CSV button only appears on the right-hand side when at least one entity has already been created. This means that the first entity created must be deleted because the import CVS button automatically generates a new entity. Now you are left with two entity type and one doesn't contain any useful information.
I suggest where the add entity button is located, you also add a Import CSV button. This way a data dictionary without attributes is not created and does not later need to be deleted.

**Comment by jlblcc** [comment]
This is a known bug. Fixed in [dev](https://dev.mdeditor.org) and will be pushed to production v.0.9.0 this week.
